###
GET http://localhost:4004/service/ServiceOrders

###
GET http://localhost:4004/service/Technicians

###
GET http://localhost:4004/service/Equipment
Accept-Language: fr

###
POST http://localhost:4004/service/ServiceOrders
Content-Type: application/json

{
  "description": "The service order from Hana"
}

###
GET http://localhost:4004/service/ServiceOrders(ID='be4b6d8f-1a3c-4e7d-9f2b-0c3e5a7d8f61')/calculateETA

###
GET http://localhost:4004/service/getExchangeRate(from='USD',to='EUR') HTTP/1.1